import React from 'react'
import Head from 'next/head'
import { Header } from './Header'

type Props = {
	children: React.ReactElement
	title: string
}

export function Layout({ children, title = 'Larri AI' }: Props) {
	return (
		<div>
			<Head>
				<title>{title}</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />

			{children}
		</div>
	)
}
